services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python KaligulaTiketsMonitor/bot.py
    autoDeploy: true

  - type: worker
    name: telegram-monitor
    env: python
    plan: free
    buildCommand: ""
    startCommand: python KaligulaTiketsMonitor/monitor.py
    autoDeploy: true
